#!/usr/bin/env python3
from __future__ import annotations
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "encyclopedia" / "pc-2013-events"
MEDIA = ROOT / "y2013-mpc-media"
MEDIA.mkdir(parents=True, exist_ok=True)

JOBS = [
    (SRC / "2013MPCDecklists.pdf", "2013 Match Play Championship.pdf"),
    (SRC / "extract" / "mpc_p09.png", "2013 Match Play Championship p09 Amar Banger LS.png"),
    (SRC / "extract" / "mpc_p10.png", "2013 Match Play Championship p10 Amar Banger DS.png"),
    (SRC / "extract" / "mpc_p17.png", "2013 Match Play Championship p17 Keith Brown LS.png"),
    (SRC / "extract" / "mpc_p18.png", "2013 Match Play Championship p18 Keith Brown DS.png"),
    (SRC / "extract" / "mpc_p25.png", "2013 Match Play Championship p25 Wayne Cullen DS.png"),
    (SRC / "extract" / "mpc_p26.png", "2013 Match Play Championship p26 Wayne Cullen LS.png"),
    (SRC / "extract" / "mpc_p01.png", "2013 Match Play Championship p01 Barry Alperstein LS.png"),
    (SRC / "extract" / "mpc_p02.png", "2013 Match Play Championship p02 Barry Alperstein DS.png"),
    (SRC / "extract" / "mpc_p03.png", "2013 Match Play Championship p03 Nicholas Amato LS.png"),
    (SRC / "extract" / "mpc_p04.png", "2013 Match Play Championship p04 Nicholas Amato DS.png"),
    (SRC / "extract" / "mpc_p05.png", "2013 Match Play Championship p05 John Anderson DS.png"),
    (SRC / "extract" / "mpc_p06.png", "2013 Match Play Championship p06 John Anderson LS.png"),
    (SRC / "extract" / "mpc_p11.png", "2013 Match Play Championship p11 Steve Baroni LS.png"),
    (SRC / "extract" / "mpc_p12.png", "2013 Match Play Championship p12 Steve Baroni DS.png"),
    (SRC / "extract" / "mpc_p13.png", "2013 Match Play Championship p13 Andrew Bollentino DS.png"),
    (SRC / "extract" / "mpc_p14.png", "2013 Match Play Championship p14 Andrew Bollentino LS.png"),
    (SRC / "extract" / "mpc_p15.png", "2013 Match Play Championship p15 Brian Brodsky LS.png"),
    (SRC / "extract" / "mpc_p16.png", "2013 Match Play Championship p16 Brian Brodsky DS.png"),
    (SRC / "extract" / "mpc_p19.png", "2013 Match Play Championship p19 Carl Buck LS.png"),
    (SRC / "extract" / "mpc_p20.png", "2013 Match Play Championship p20 Carl Buck DS.png"),
    (SRC / "extract" / "mpc_p21.png", "2013 Match Play Championship p21 Matt Carulli DS.png"),
    (SRC / "extract" / "mpc_p22.png", "2013 Match Play Championship p22 Matt Carulli LS.png"),
    (SRC / "extract" / "mpc_p07.png", "2013 Match Play Championship p07 Casey Anis DS.png"),
    (SRC / "extract" / "mpc_p08.png", "2013 Match Play Championship p08 Casey Anis LS.png"),
    (SRC / "extract" / "mpc_p23.png", "2013 Match Play Championship p23 Justin Carulli DS.png"),
    (SRC / "extract" / "mpc_p24.png", "2013 Match Play Championship p24 Justin Carulli LS.png"),
    (SRC / "extract" / "mpc_p41.png", "2013 Match Play Championship p41 Jerry Heine DS.png"),
    (SRC / "extract" / "mpc_p42.png", "2013 Match Play Championship p42 Jerry Heine LS.png"),
    (SRC / "extract" / "mpc_p39.png", "2013 Match Play Championship p39 Matthew Harrison-Trainor DS.png"),
    (SRC / "extract" / "mpc_p40.png", "2013 Match Play Championship p40 Matthew Harrison-Trainor LS.png"),
    (SRC / "extract" / "mpc_p45.png", "2013 Match Play Championship p45 Brian Hunter LS.png"),
    (SRC / "extract" / "mpc_p46.png", "2013 Match Play Championship p46 Brian Hunter DS.png"),
    (SRC / "extract" / "mpc_p43.png", "2013 Match Play Championship p43 Brian Herold LS.png"),
    (SRC / "extract" / "mpc_p44.png", "2013 Match Play Championship p44 Brian Herold DS.png"),
    (SRC / "extract" / "mpc_p55.png", "2013 Match Play Championship p55 Cole Lepine DS.png"),
    (SRC / "extract" / "mpc_p56.png", "2013 Match Play Championship p56 Cole Lepine LS.png"),
    (SRC / "extract" / "mpc_p61.png", "2013 Match Play Championship p61 Sam Marlow DS.png"),
    (SRC / "extract" / "mpc_p62.png", "2013 Match Play Championship p62 Sam Marlow LS.png"),
    (SRC / "extract" / "mpc_p71.png", "2013 Match Play Championship p71 Joe Pinto LS.png"),
    (SRC / "extract" / "mpc_p72.png", "2013 Match Play Championship p72 Joe Pinto DS.png"),
    (SRC / "extract" / "mpc_p99.png", "2013 Match Play Championship p99 Mike Tomashewski LS.png"),
    (SRC / "extract" / "mpc_p100.png", "2013 Match Play Championship p100 Mike Tomashewski DS.png"),
    (SRC / "extract" / "mpc_p105.png", "2013 Match Play Championship p105 Chris Westergard LS.png"),
    (SRC / "extract" / "mpc_p106.png", "2013 Match Play Championship p106 Chris Westergard DS.png"),
    (SRC / "extract" / "mpc_p27.png", "2013 Match Play Championship p27 Mike D'Ambrosio DS.png"),
    (SRC / "extract" / "mpc_p28.png", "2013 Match Play Championship p28 Mike D'Ambrosio LS.png"),
    (SRC / "extract" / "mpc_p57.png", "2013 Match Play Championship p57 Scott Lingrell DS.png"),
    (SRC / "extract" / "mpc_p58.png", "2013 Match Play Championship p58 Scott Lingrell LS.png"),
    (SRC / "extract" / "mpc_p75.png", "2013 Match Play Championship p75 Nick Reisch LS.png"),
    (SRC / "extract" / "mpc_p76.png", "2013 Match Play Championship p76 Nick Reisch DS.png"),
    (SRC / "extract" / "mpc_p85.png", "2013 Match Play Championship p85 Greg Shaw DS.png"),
    (SRC / "extract" / "mpc_p86.png", "2013 Match Play Championship p86 Greg Shaw LS.png"),
    (SRC / "extract" / "mpc_p93.png", "2013 Match Play Championship p93 Peter Tenneson LS.png"),
    (SRC / "extract" / "mpc_p94.png", "2013 Match Play Championship p94 Peter Tenneson DS.png"),
    (SRC / "extract" / "mpc_p97.png", "2013 Match Play Championship p97 Michael Thomas LS.png"),
    (SRC / "extract" / "mpc_p98.png", "2013 Match Play Championship p98 Michael Thomas DS.png"),
    (SRC / "extract" / "mpc_p103.png", "2013 Match Play Championship p103 John Veasey LS.png"),
    (SRC / "extract" / "mpc_p104.png", "2013 Match Play Championship p104 John Veasey DS.png"),
    (SRC / "extract" / "mpc_p29.png", "2013 Match Play Championship p29 Matt Fink LS.png"),
    (SRC / "extract" / "mpc_p30.png", "2013 Match Play Championship p30 Matt Fink DS.png"),
    (SRC / "extract" / "mpc_p49.png", "2013 Match Play Championship p49 Aaron Kinser LS.png"),
    (SRC / "extract" / "mpc_p50.png", "2013 Match Play Championship p50 Aaron Kinser DS.png"),
    (SRC / "extract" / "mpc_p53.png", "2013 Match Play Championship p53 Tuan Le DS.png"),
    (SRC / "extract" / "mpc_p54.png", "2013 Match Play Championship p54 Tuan Le LS.png"),
    (SRC / "extract" / "mpc_p59.png", "2013 Match Play Championship p59 Josh Mack DS.png"),
    (SRC / "extract" / "mpc_p60.png", "2013 Match Play Championship p60 Josh Mack LS.png"),
    (SRC / "extract" / "mpc_p63.png", "2013 Match Play Championship p63 Aaron Nelson LS.png"),
    (SRC / "extract" / "mpc_p64.png", "2013 Match Play Championship p64 Aaron Nelson DS.png"),
    (SRC / "extract" / "mpc_p65.png", "2013 Match Play Championship p65 Cuong Nguyen DS.png"),
    (SRC / "extract" / "mpc_p66.png", "2013 Match Play Championship p66 Cuong Nguyen LS.png"),
    (SRC / "extract" / "mpc_p67.png", "2013 Match Play Championship p67 Chris O'Hara DS.png"),
    (SRC / "extract" / "mpc_p68.png", "2013 Match Play Championship p68 Chris O'Hara LS.png"),
    (SRC / "extract" / "mpc_p69.png", "2013 Match Play Championship p69 Matt Paragano DS.png"),
    (SRC / "extract" / "mpc_p70.png", "2013 Match Play Championship p70 Matt Paragano LS.png"),
    (SRC / "extract" / "mpc_p77.png", "2013 Match Play Championship p77 Mike Richards LS.png"),
    (SRC / "extract" / "mpc_p78.png", "2013 Match Play Championship p78 Mike Richards DS.png"),
    (SRC / "extract" / "mpc_p83.png", "2013 Match Play Championship p83 Rustin Sharer DS.png"),
    (SRC / "extract" / "mpc_p84.png", "2013 Match Play Championship p84 Rustin Sharer LS.png"),
    (SRC / "extract" / "mpc_p31.png", "2013 Match Play Championship p31 Tony G LS.png"),
    (SRC / "extract" / "mpc_p32.png", "2013 Match Play Championship p32 Tony G DS.png"),
    (SRC / "extract" / "mpc_p33.png", "2013 Match Play Championship p33 Jeremy G DS.png"),
    (SRC / "extract" / "mpc_p34.png", "2013 Match Play Championship p34 Jeremy G LS.png"),
    (SRC / "extract" / "mpc_p35.png", "2013 Match Play Championship p35 Gogolen LS.png"),
    (SRC / "extract" / "mpc_p36.png", "2013 Match Play Championship p36 Gogolen DS.png"),
    (SRC / "extract" / "mpc_p37.png", "2013 Match Play Championship p37 HARPSTER LS.png"),
    (SRC / "extract" / "mpc_p38.png", "2013 Match Play Championship p38 HARPSTER DS.png"),
    (SRC / "extract" / "mpc_p47.png", "2013 Match Play Championship p47 Stephen Kin LS.png"),
    (SRC / "extract" / "mpc_p48.png", "2013 Match Play Championship p48 Stephen Kin DS.png"),
    (SRC / "extract" / "mpc_p51.png", "2013 Match Play Championship p51 Jared DS.png"),
    (SRC / "extract" / "mpc_p52.png", "2013 Match Play Championship p52 Jared LS.png"),
    (SRC / "extract" / "mpc_p73.png", "2013 Match Play Championship p73 Pistone LS.png"),
    (SRC / "extract" / "mpc_p74.png", "2013 Match Play Championship p74 Pistone DS.png"),
    (SRC / "extract" / "mpc_p79.png", "2013 Match Play Championship p79 Schwartz LS.png"),
    (SRC / "extract" / "mpc_p80.png", "2013 Match Play Championship p80 Schwartz DS.png"),
    (SRC / "extract" / "mpc_p81.png", "2013 Match Play Championship p81 Shannon DS.png"),
    (SRC / "extract" / "mpc_p82.png", "2013 Match Play Championship p82 Shannon LS.png"),
    (SRC / "extract" / "mpc_p87.png", "2013 Match Play Championship p87 Steve S. LS.png"),
    (SRC / "extract" / "mpc_p88.png", "2013 Match Play Championship p88 Steve S. DS.png"),
    (SRC / "extract" / "mpc_p89.png", "2013 Match Play Championship p89 Smith DS.png"),
    (SRC / "extract" / "mpc_p90.png", "2013 Match Play Championship p90 Smith LS.png"),
    (SRC / "extract" / "mpc_p91.png", "2013 Match Play Championship p91 Sokol LS.png"),
    (SRC / "extract" / "mpc_p92.png", "2013 Match Play Championship p92 Sokol DS.png"),
    (SRC / "extract" / "mpc_p95.png", "2013 Match Play Championship p95 BTwigg DS.png"),
    (SRC / "extract" / "mpc_p96.png", "2013 Match Play Championship p96 BTwigg LS.png"),
    (SRC / "extract" / "mpc_p101.png", "2013 Match Play Championship p101 Mauer LS.png"),
    (SRC / "extract" / "mpc_p102.png", "2013 Match Play Championship p102 Mauer DS.png"),
    (SRC / "extract" / "mpc_p107.png", "2013 Match Play Championship p107 SAN LS.png"),
    (SRC / "extract" / "mpc_p108.png", "2013 Match Play Championship p108 SAN DS.png"),
    (SRC / "extract" / "mpc_p109.png", "2013 Match Play Championship p109 Micah Wall LS.png"),
    (SRC / "extract" / "mpc_p110.png", "2013 Match Play Championship p110 Micah Wall DS.png"),
    (SRC / "extract" / "mpc_p111.png", "2013 Match Play Championship p111 Steve Wall DS.png"),
    (SRC / "extract" / "mpc_p112.png", "2013 Match Play Championship p112 Steve Wall LS.png"),
    (SRC / "extract" / "mpc_p113.png", "2013 Match Play Championship p113 Alex W LS.png"),
    (SRC / "extract" / "mpc_p114.png", "2013 Match Play Championship p114 Alex W DS.png"),
    (SRC / "extract" / "mpc_p115.png", "2013 Match Play Championship p115 WIRFS DS.png"),
    (SRC / "extract" / "mpc_p116.png", "2013 Match Play Championship p116 WIRFS LS.png"),
]
for src, name in JOBS:
    dest = MEDIA / name
    if not src.exists():
        raise SystemExit(f"missing {src}")
    shutil.copy2(src, dest)
    print("copy", dest.name, dest.stat().st_size)
print("DONE", MEDIA)
