#!/usr/bin/env python3
from __future__ import annotations
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "encyclopedia" / "pc-2012-events"
MEDIA = ROOT / "y2012-mpc-media"
MEDIA.mkdir(parents=True, exist_ok=True)

JOBS = [
    (SRC / "2012mpcday1.pdf", "2012 Match Play Championship Day 1.pdf"),
    (SRC / "extract" / "mpc_d1_p01.png", "2012 Match Play Championship Day 1 Chris Erwin DS.png"),
    (SRC / "extract" / "mpc_d1_p02.png", "2012 Match Play Championship Day 1 Chris Erwin LS.png"),
    (SRC / "extract" / "mpc_d1_p03.png", "2012 Match Play Championship Day 1 Scott Lingrell LS.png"),
    (SRC / "extract" / "mpc_d1_p04.png", "2012 Match Play Championship Day 1 Scott Lingrell DS.png"),
    (SRC / "extract" / "mpc_d1_p05.png", "2012 Match Play Championship Day 1 Brian Field DS.png"),
    (SRC / "extract" / "mpc_d1_p06.png", "2012 Match Play Championship Day 1 Brian Field LS.png"),
    (SRC / "extract" / "mpc_d1_p07.png", "2012 Match Play Championship Day 1 Matthew Harrison-Trainor LS.png"),
    (SRC / "extract" / "mpc_d1_p08.png", "2012 Match Play Championship Day 1 Matthew Harrison-Trainor DS.png"),
    (SRC / "extract" / "mpc_d1_p09.png", "2012 Match Play Championship Day 1 Kevin Shannon DS.png"),
    (SRC / "extract" / "mpc_d1_p10.png", "2012 Match Play Championship Day 1 Kevin Shannon LS.png"),
    (SRC / "extract" / "mpc_d1_p11.png", "2012 Match Play Championship Day 1 Matt Sokol DS.png"),
    (SRC / "extract" / "mpc_d1_p12.png", "2012 Match Play Championship Day 1 Matt Sokol LS.png"),
    (SRC / "extract" / "mpc_d1_p13.png", "2012 Match Play Championship Day 1 Greg Shaw DS.png"),
    (SRC / "extract" / "mpc_d1_p14.png", "2012 Match Play Championship Day 1 Greg Shaw LS.png"),
    (SRC / "extract" / "mpc_d1_p15.png", "2012 Match Play Championship Day 1 Cole Lepine DS.png"),
    (SRC / "extract" / "mpc_d1_p16.png", "2012 Match Play Championship Day 1 Cole Lepine LS.png"),
    (SRC / "extract" / "mpc_d1_p19.png", "2012 Match Play Championship Day 1 Jonny Chu LS.png"),
    (SRC / "extract" / "mpc_d1_p20.png", "2012 Match Play Championship Day 1 Jonny Chu DS.png"),
    (SRC / "extract" / "mpc_d1_p21.png", "2012 Match Play Championship Day 1 Brad Eier DS.png"),
    (SRC / "extract" / "mpc_d1_p22.png", "2012 Match Play Championship Day 1 Brad Eier LS.png"),
    (SRC / "extract" / "mpc_d1_p23.png", "2012 Match Play Championship Day 1 Aaron Nelson DS.png"),
    (SRC / "extract" / "mpc_d1_p24.png", "2012 Match Play Championship Day 1 Aaron Nelson LS.png"),
    (SRC / "extract" / "mpc_d1_p25.png", "2012 Match Play Championship Day 1 Steve Baroni DS.png"),
    (SRC / "extract" / "mpc_d1_p26.png", "2012 Match Play Championship Day 1 Steve Baroni LS.png"),
    (SRC / "extract" / "mpc_d1_p27.png", "2012 Match Play Championship Day 1 Brian Terwilliger DS.png"),
    (SRC / "extract" / "mpc_d1_p28.png", "2012 Match Play Championship Day 1 Brian Terwilliger LS.png"),
    (SRC / "extract" / "mpc_d1_p29.png", "2012 Match Play Championship Day 1 Caleb Foth DS.png"),
    (SRC / "extract" / "mpc_d1_p30.png", "2012 Match Play Championship Day 1 Caleb Foth LS.png"),
    (SRC / "extract" / "mpc_d1_p31.png", "2012 Match Play Championship Day 1 Steve Harpster DS.png"),
    (SRC / "extract" / "mpc_d1_p32.png", "2012 Match Play Championship Day 1 Steve Harpster LS.png"),
    (SRC / "extract" / "mpc_d1_p33.png", "2012 Match Play Championship Day 1 Barry Alperstein DS.png"),
    (SRC / "extract" / "mpc_d1_p34.png", "2012 Match Play Championship Day 1 Barry Alperstein LS.png"),
    (SRC / "extract" / "mpc_d1_p35.png", "2012 Match Play Championship Day 1 John Anderson LS.png"),
    (SRC / "extract" / "mpc_d1_p36.png", "2012 Match Play Championship Day 1 John Anderson DS.png"),
    (SRC / "extract" / "mpc_d1_p37.png", "2012 Match Play Championship Day 1 Casey Anis LS.png"),
    (SRC / "extract" / "mpc_d1_p38.png", "2012 Match Play Championship Day 1 Casey Anis DS.png"),
    (SRC / "extract" / "mpc_d1_p39.png", "2012 Match Play Championship Day 1 Nicholas Amato LS.png"),
    (SRC / "extract" / "mpc_d1_p40.png", "2012 Match Play Championship Day 1 Nicholas Amato DS.png"),
    (SRC / "extract" / "mpc_d1_p41.png", "2012 Match Play Championship Day 1 Clayton Atkin LS.png"),
    (SRC / "extract" / "mpc_d1_p42.png", "2012 Match Play Championship Day 1 Clayton Atkin DS.png"),
    (SRC / "extract" / "mpc_d1_p43.png", "2012 Match Play Championship Day 1 Vikram Bali LS.png"),
    (SRC / "extract" / "mpc_d1_p44.png", "2012 Match Play Championship Day 1 Vikram Bali DS.png"),
    (SRC / "extract" / "mpc_d1_p45.png", "2012 Match Play Championship Day 1 Amar Banger LS.png"),
    (SRC / "extract" / "mpc_d1_p46.png", "2012 Match Play Championship Day 1 Amar Banger DS.png"),
    (SRC / "extract" / "mpc_d1_p47.png", "2012 Match Play Championship Day 1 James Booker LS.png"),
    (SRC / "extract" / "mpc_d1_p48.png", "2012 Match Play Championship Day 1 James Booker DS.png"),
    (SRC / "extract" / "mpc_d1_p49.png", "2012 Match Play Championship Day 1 Andrew Bollentino LS.png"),
    (SRC / "extract" / "mpc_d1_p50.png", "2012 Match Play Championship Day 1 Andrew Bollentino DS.png"),
    (SRC / "extract" / "mpc_d1_p51.png", "2012 Match Play Championship Day 1 Roy Bordier LS.png"),
    (SRC / "extract" / "mpc_d1_p52.png", "2012 Match Play Championship Day 1 Roy Bordier DS.png"),
    (SRC / "extract" / "mpc_d1_p53.png", "2012 Match Play Championship Day 1 Brian Brodsky LS.png"),
    (SRC / "extract" / "mpc_d1_p54.png", "2012 Match Play Championship Day 1 Brian Brodsky DS.png"),
    (SRC / "extract" / "mpc_d1_p55.png", "2012 Match Play Championship Day 1 Ben Brummett LS.png"),
    (SRC / "extract" / "mpc_d1_p56.png", "2012 Match Play Championship Day 1 Ben Brummett DS.png"),
    (SRC / "extract" / "mpc_d1_p57.png", "2012 Match Play Championship Day 1 Carl Buck LS.png"),
    (SRC / "extract" / "mpc_d1_p58.png", "2012 Match Play Championship Day 1 Carl Buck DS.png"),
    (SRC / "extract" / "mpc_d1_p59.png", "2012 Match Play Championship Day 1 Justin Carulli LS.png"),
    (SRC / "extract" / "mpc_d1_p60.png", "2012 Match Play Championship Day 1 Justin Carulli DS.png"),
    (SRC / "extract" / "mpc_d1_p61.png", "2012 Match Play Championship Day 1 Wayne Cullen LS.png"),
    (SRC / "extract" / "mpc_d1_p62.png", "2012 Match Play Championship Day 1 Wayne Cullen DS.png"),
    (SRC / "extract" / "mpc_d1_p63.png", "2012 Match Play Championship Day 1 Dalton LS.png"),
    (SRC / "extract" / "mpc_d1_p64.png", "2012 Match Play Championship Day 1 Dalton DS.png"),
    (SRC / "extract" / "mpc_d1_p65.png", "2012 Match Play Championship Day 1 Philippe Dubreuil LS.png"),
    (SRC / "extract" / "mpc_d1_p66.png", "2012 Match Play Championship Day 1 Philippe Dubreuil DS.png"),
    (SRC / "extract" / "mpc_d1_p67.png", "2012 Match Play Championship Day 1 Pierre Dubreuil LS.png"),
    (SRC / "extract" / "mpc_d1_p68.png", "2012 Match Play Championship Day 1 Pierre Dubreuil DS.png"),
    (SRC / "extract" / "mpc_d1_p69.png", "2012 Match Play Championship Day 1 Chuck Finley LS.png"),
    (SRC / "extract" / "mpc_d1_p70.png", "2012 Match Play Championship Day 1 Chuck Finley DS.png"),
    (SRC / "extract" / "mpc_d1_p71.png", "2012 Match Play Championship Day 1 Tony Garcia LS.png"),
    (SRC / "extract" / "mpc_d1_p72.png", "2012 Match Play Championship Day 1 Tony Garcia DS.png"),
    (SRC / "extract" / "mpc_d1_p73.png", "2012 Match Play Championship Day 1 Mike Gemme LS.png"),
    (SRC / "extract" / "mpc_d1_p74.png", "2012 Match Play Championship Day 1 Mike Gemme DS.png"),
    (SRC / "extract" / "mpc_d1_p75.png", "2012 Match Play Championship Day 1 Chris Gogolen LS.png"),
    (SRC / "extract" / "mpc_d1_p76.png", "2012 Match Play Championship Day 1 Chris Gogolen DS.png"),
    (SRC / "extract" / "mpc_d1_p77.png", "2012 Match Play Championship Day 1 Matt Gombos LS.png"),
    (SRC / "extract" / "mpc_d1_p78.png", "2012 Match Play Championship Day 1 Matt Gombos DS.png"),
    (SRC / "extract" / "mpc_d1_p79.png", "2012 Match Play Championship Day 1 Thomas Graham LS.png"),
    (SRC / "extract" / "mpc_d1_p80.png", "2012 Match Play Championship Day 1 Thomas Graham DS.png"),
    (SRC / "extract" / "mpc_d1_p81.png", "2012 Match Play Championship Day 1 Brian Herold LS.png"),
    (SRC / "extract" / "mpc_d1_p82.png", "2012 Match Play Championship Day 1 Brian Herold DS.png"),
    (SRC / "extract" / "mpc_d1_p83.png", "2012 Match Play Championship Day 1 Greg Hodur LS.png"),
    (SRC / "extract" / "mpc_d1_p84.png", "2012 Match Play Championship Day 1 Greg Hodur DS.png"),
    (SRC / "extract" / "mpc_d1_p85.png", "2012 Match Play Championship Day 1 Brian Hollingworth LS.png"),
    (SRC / "extract" / "mpc_d1_p86.png", "2012 Match Play Championship Day 1 Brian Hollingworth DS.png"),
    (SRC / "extract" / "mpc_d1_p87.png", "2012 Match Play Championship Day 1 Adam Howland LS.png"),
    (SRC / "extract" / "mpc_d1_p88.png", "2012 Match Play Championship Day 1 Adam Howland DS.png"),
    (SRC / "extract" / "mpc_d1_p89.png", "2012 Match Play Championship Day 1 Hayes Hunter LS.png"),
    (SRC / "extract" / "mpc_d1_p90.png", "2012 Match Play Championship Day 1 Hayes Hunter DS.png"),
    (SRC / "extract" / "mpc_d1_p91.png", "2012 Match Play Championship Day 1 Steve Skilton LS.png"),
    (SRC / "extract" / "mpc_d1_p92.png", "2012 Match Play Championship Day 1 Steve Skilton DS.png"),
    (SRC / "extract" / "mpc_d1_p93.png", "2012 Match Play Championship Day 1 PMT LS.png"),
    (SRC / "extract" / "mpc_d1_p94.png", "2012 Match Play Championship Day 1 PMT DS.png"),
    (SRC / "extract" / "mpc_d1_p95.png", "2012 Match Play Championship Day 1 Wojciech Jankowski LS.png"),
    (SRC / "extract" / "mpc_d1_p96.png", "2012 Match Play Championship Day 1 Wojciech Jankowski DS.png"),
    (SRC / "extract" / "mpc_d1_p97.png", "2012 Match Play Championship Day 1 Matt Jourdan LS.png"),
    (SRC / "extract" / "mpc_d1_p98.png", "2012 Match Play Championship Day 1 Matt Jourdan DS.png"),
    (SRC / "extract" / "mpc_d1_p99.png", "2012 Match Play Championship Day 1 Chris Kelly LS.png"),
    (SRC / "extract" / "mpc_d1_p100.png", "2012 Match Play Championship Day 1 Chris Kelly DS.png"),
    (SRC / "extract" / "mpc_d1_p101.png", "2012 Match Play Championship Day 1 Mike Kessling LS.png"),
    (SRC / "extract" / "mpc_d1_p102.png", "2012 Match Play Championship Day 1 Mike Kessling DS.png"),
    (SRC / "extract" / "mpc_d1_p103.png", "2012 Match Play Championship Day 1 Aaron Kinsey LS.png"),
    (SRC / "extract" / "mpc_d1_p104.png", "2012 Match Play Championship Day 1 Aaron Kinsey DS.png"),
    (SRC / "extract" / "mpc_d1_p105.png", "2012 Match Play Championship Day 1 Jared LS.png"),
    (SRC / "extract" / "mpc_d1_p106.png", "2012 Match Play Championship Day 1 Jared DS.png"),
    (SRC / "extract" / "mpc_d1_p108.png", "2012 Match Play Championship Day 1 Kyle Krueger LS.png"),
    (SRC / "extract" / "mpc_d1_p107.png", "2012 Match Play Championship Day 1 Kyle Krueger DS.png"),
    (SRC / "extract" / "mpc_d1_p109.png", "2012 Match Play Championship Day 1 Josh Mack LS.png"),
    (SRC / "extract" / "mpc_d1_p110.png", "2012 Match Play Championship Day 1 Josh Mack DS.png"),
    (SRC / "extract" / "mpc_d1_p111.png", "2012 Match Play Championship Day 1 Sam Marlow LS.png"),
    (SRC / "extract" / "mpc_d1_p112.png", "2012 Match Play Championship Day 1 Sam Marlow DS.png"),
    (SRC / "extract" / "mpc_d1_p113.png", "2012 Match Play Championship Day 1 Justin Montgomery LS.png"),
    (SRC / "extract" / "mpc_d1_p114.png", "2012 Match Play Championship Day 1 Justin Montgomery DS.png"),
    (SRC / "extract" / "mpc_d1_p115.png", "2012 Match Play Championship Day 1 Tim Murray LS.png"),
    (SRC / "extract" / "mpc_d1_p116.png", "2012 Match Play Championship Day 1 Tim Murray DS.png"),
    (SRC / "extract" / "mpc_d1_p117.png", "2012 Match Play Championship Day 1 Chris O'Hare LS.png"),
    (SRC / "extract" / "mpc_d1_p118.png", "2012 Match Play Championship Day 1 Chris O'Hare DS.png"),
    (SRC / "extract" / "mpc_d1_p119.png", "2012 Match Play Championship Day 1 Joe Pinto LS.png"),
    (SRC / "extract" / "mpc_d1_p120.png", "2012 Match Play Championship Day 1 Joe Pinto DS.png"),
    (SRC / "extract" / "mpc_d1_p121.png", "2012 Match Play Championship Day 1 Mike Pistone LS.png"),
    (SRC / "extract" / "mpc_d1_p122.png", "2012 Match Play Championship Day 1 Mike Pistone DS.png"),
    (SRC / "extract" / "mpc_d1_p123.png", "2012 Match Play Championship Day 1 Mike Richards LS.png"),
    (SRC / "extract" / "mpc_d1_p124.png", "2012 Match Play Championship Day 1 Mike Richards DS.png"),
    (SRC / "extract" / "mpc_d1_p125.png", "2012 Match Play Championship Day 1 Chris Schoenthal LS.png"),
    (SRC / "extract" / "mpc_d1_p126.png", "2012 Match Play Championship Day 1 Chris Schoenthal DS.png"),
    (SRC / "extract" / "mpc_d1_p127.png", "2012 Match Play Championship Day 1 Reid Smith LS.png"),
    (SRC / "extract" / "mpc_d1_p128.png", "2012 Match Play Championship Day 1 Reid Smith DS.png"),
    (SRC / "extract" / "mpc_d1_p129.png", "2012 Match Play Championship Day 1 Pete Srodoski LS.png"),
    (SRC / "extract" / "mpc_d1_p130.png", "2012 Match Play Championship Day 1 Pete Srodoski DS.png"),
    (SRC / "extract" / "mpc_d1_p131.png", "2012 Match Play Championship Day 1 Matt Thornton LS.png"),
    (SRC / "extract" / "mpc_d1_p132.png", "2012 Match Play Championship Day 1 Matt Thornton DS.png"),
    (SRC / "extract" / "mpc_d1_p133.png", "2012 Match Play Championship Day 1 Marty Terwilliger LS.png"),
    (SRC / "extract" / "mpc_d1_p134.png", "2012 Match Play Championship Day 1 Marty Terwilliger DS.png"),
    (SRC / "extract" / "mpc_d1_p135.png", "2012 Match Play Championship Day 1 Michael Thomas LS.png"),
    (SRC / "extract" / "mpc_d1_p136.png", "2012 Match Play Championship Day 1 Michael Thomas DS.png"),
    (SRC / "extract" / "mpc_d1_p137.png", "2012 Match Play Championship Day 1 Chris Terwilliger LS.png"),
    (SRC / "extract" / "mpc_d1_p138.png", "2012 Match Play Championship Day 1 Chris Terwilliger DS.png"),
    (SRC / "extract" / "mpc_d1_p139.png", "2012 Match Play Championship Day 1 John Veasey LS.png"),
    (SRC / "extract" / "mpc_d1_p140.png", "2012 Match Play Championship Day 1 John Veasey DS.png"),
    (SRC / "extract" / "mpc_d1_p141.png", "2012 Match Play Championship Day 1 Alex W DS.png"),
    (SRC / "extract" / "mpc_d1_p142.png", "2012 Match Play Championship Day 1 Alex W LS.png"),
    (SRC / "extract" / "mpc_d1_p143.png", "2012 Match Play Championship Day 1 Chris Westergard LS.png"),
    (SRC / "extract" / "mpc_d1_p144.png", "2012 Match Play Championship Day 1 Chris Westergard DS.png"),
    (SRC / "extract" / "mpc_d1_p145.png", "2012 Match Play Championship Day 1 SAN LS.png"),
    (SRC / "extract" / "mpc_d1_p146.png", "2012 Match Play Championship Day 1 SAN DS.png"),
    (SRC / "extract" / "mpc_d1_p147.png", "2012 Match Play Championship Day 1 Chris Wirfs LS.png"),
    (SRC / "extract" / "mpc_d1_p148.png", "2012 Match Play Championship Day 1 Chris Wirfs DS.png"),
    (SRC / "extract" / "mpc_d1_p149.png", "2012 Match Play Championship Day 1 Patrick Ziagos LS.png"),
    (SRC / "extract" / "mpc_d1_p150.png", "2012 Match Play Championship Day 1 Patrick Ziagos DS.png"),
    (SRC / "extract" / "mpc_d1_p151.png", "2012 Match Play Championship Day 1 light_frank LS.png"),
    (SRC / "extract" / "mpc_d1_p153.png", "2012 Match Play Championship Day 1 light_frank DS.png"),
    (SRC / "extract" / "mpc_d1_p155.png", "2012 Match Play Championship Day 1 Unknown Player LS.png"),
    (SRC / "extract" / "mpc_d1_p156.png", "2012 Match Play Championship Day 1 Unknown Player DS.png"),
    (SRC / "2012mpcday2.pdf", "2012 Match Play Championship Day 2.pdf"),
    (SRC / "extract" / "mpc_d2_p01.png", "2012 Match Play Championship Day 2 Aaron Nelson LS.png"),
    (SRC / "extract" / "mpc_d2_p02.png", "2012 Match Play Championship Day 2 Aaron Nelson DS.png"),
    (SRC / "extract" / "mpc_d2_p03.png", "2012 Match Play Championship Day 2 Greg Shaw DS.png"),
    (SRC / "extract" / "mpc_d2_p04.png", "2012 Match Play Championship Day 2 Greg Shaw LS.png"),
    (SRC / "extract" / "mpc_d2_p05.png", "2012 Match Play Championship Day 2 Steve Harpster LS.png"),
    (SRC / "extract" / "mpc_d2_p06.png", "2012 Match Play Championship Day 2 Steve Harpster DS.png"),
    (SRC / "extract" / "mpc_d2_p07.png", "2012 Match Play Championship Day 2 Brian Fred LS.png"),
    (SRC / "extract" / "mpc_d2_p08.png", "2012 Match Play Championship Day 2 Brian Fred DS.png"),
    (SRC / "extract" / "mpc_d2_p09.png", "2012 Match Play Championship Day 2 Steve Baroni DS.png"),
    (SRC / "extract" / "mpc_d2_p11.png", "2012 Match Play Championship Day 2 Jonny Chu LS.png"),
    (SRC / "extract" / "mpc_d2_p12.png", "2012 Match Play Championship Day 2 Jonny Chu DS.png"),
    (SRC / "extract" / "mpc_d2_p13.png", "2012 Match Play Championship Day 2 Cole Lepine DS.png"),
    (SRC / "extract" / "mpc_d2_p14.png", "2012 Match Play Championship Day 2 Cole Lepine LS.png"),
    (SRC / "extract" / "mpc_d2_p15.png", "2012 Match Play Championship Day 2 Kevin Shannon LS.png"),
    (SRC / "extract" / "mpc_d2_p16.png", "2012 Match Play Championship Day 2 Kevin Shannon DS.png"),
]
for src, name in JOBS:
    dest = MEDIA / name
    shutil.copy2(src, dest)
    print("copied", dest.name, dest.stat().st_size)
