#!/usr/bin/env python3
from __future__ import annotations
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "encyclopedia" / "pc-2012-events"
MEDIA = ROOT / "y2012-nats-media"
MEDIA.mkdir(parents=True, exist_ok=True)

JOBS = [
    (SRC / "2012NationalsDay1.pdf", "2012 US Nationals Day 1.pdf"),
    (SRC / "2012NationalsDay2.pdf", "2012 US Nationals Day 2.pdf"),
    (SRC / "extract" / "nats_d1_p01.png", "2012 US Nationals Day 1 John Anderson DS.png"),
    (SRC / "extract" / "nats_d1_p02.png", "2012 US Nationals Day 1 John Anderson LS.png"),
    (SRC / "extract" / "nats_d1_p03.png", "2012 US Nationals Day 1 Devin Aue LS.png"),
    (SRC / "extract" / "nats_d1_p04.png", "2012 US Nationals Day 1 Devin Aue DS.png"),
    (SRC / "extract" / "nats_d1_p05.png", "2012 US Nationals Day 1 Grant B LS.png"),
    (SRC / "extract" / "nats_d1_p06.png", "2012 US Nationals Day 1 Grant B DS.png"),
    (SRC / "extract" / "nats_d1_p07.png", "2012 US Nationals Day 1 Jan B LS.png"),
    (SRC / "extract" / "nats_d1_p08.png", "2012 US Nationals Day 1 Jan B DS.png"),
    (SRC / "extract" / "nats_d1_p09.png", "2012 US Nationals Day 1 Brandon Burgt DS.png"),
    (SRC / "extract" / "nats_d1_p10.png", "2012 US Nationals Day 1 Brandon Burgt LS.png"),
    (SRC / "extract" / "nats_d1_p11.png", "2012 US Nationals Day 1 Angelo Consoli LS.png"),
    (SRC / "extract" / "nats_d1_p12.png", "2012 US Nationals Day 1 Angelo Consoli DS.png"),
    (SRC / "extract" / "nats_d1_p13.png", "2012 US Nationals Day 1 Cooleo DS.png"),
    (SRC / "extract" / "nats_d1_p14.png", "2012 US Nationals Day 1 Cooleo LS.png"),
    (SRC / "extract" / "nats_d1_p15.png", "2012 US Nationals Day 1 Jessica Echeverria LS.png"),
    (SRC / "extract" / "nats_d1_p16.png", "2012 US Nationals Day 1 Jessica Echeverria DS.png"),
    (SRC / "extract" / "nats_d1_p17.png", "2012 US Nationals Day 1 Peter Grouty DS.png"),
    (SRC / "extract" / "nats_d1_p18.png", "2012 US Nationals Day 1 Peter Grouty LS.png"),
    (SRC / "extract" / "nats_d1_p19.png", "2012 US Nationals Day 1 Tom Frafjord DS.png"),
    (SRC / "extract" / "nats_d1_p20.png", "2012 US Nationals Day 1 Tom Frafjord LS.png"),
    (SRC / "extract" / "nats_d1_p21.png", "2012 US Nationals Day 1 Fernando LS.png"),
    (SRC / "extract" / "nats_d1_p22.png", "2012 US Nationals Day 1 Fernando DS.png"),
    (SRC / "extract" / "nats_d1_p23.png", "2012 US Nationals Day 1 George LS.png"),
    (SRC / "extract" / "nats_d1_p24.png", "2012 US Nationals Day 1 George DS.png"),
    (SRC / "extract" / "nats_d1_p25.png", "2012 US Nationals Day 1 Chris Haglund LS.png"),
    (SRC / "extract" / "nats_d1_p25.png", "2012 US Nationals Day 1 Chris Haglund DS.png"),
    (SRC / "extract" / "nats_d1_p26.png", "2012 US Nationals Day 1 Matt Hanson DS.png"),
    (SRC / "extract" / "nats_d1_p27.png", "2012 US Nationals Day 1 Matt Hanson LS.png"),
    (SRC / "extract" / "nats_d1_p28.png", "2012 US Nationals Day 1 Marc Hanson LS.png"),
    (SRC / "extract" / "nats_d1_p29.png", "2012 US Nationals Day 1 Marc Hanson DS.png"),
    (SRC / "extract" / "nats_d1_p30.png", "2012 US Nationals Day 1 Brian Herold LS.png"),
    (SRC / "extract" / "nats_d1_p31.png", "2012 US Nationals Day 1 Brian Herold DS.png"),
    (SRC / "extract" / "nats_d1_p32.png", "2012 US Nationals Day 1 Jeeps LS.png"),
    (SRC / "extract" / "nats_d1_p33.png", "2012 US Nationals Day 1 Jeeps DS.png"),
    (SRC / "extract" / "nats_d1_p34.png", "2012 US Nationals Day 1 Calvin Kurten LS.png"),
    (SRC / "extract" / "nats_d1_p35.png", "2012 US Nationals Day 1 Calvin Kurten DS.png"),
    (SRC / "extract" / "nats_d1_p36.png", "2012 US Nationals Day 1 Bryan McCune DS.png"),
    (SRC / "extract" / "nats_d1_p37.png", "2012 US Nationals Day 1 Bryan McCune LS.png"),
    (SRC / "extract" / "nats_d1_p38.png", "2012 US Nationals Day 1 Orlie Martin LS.png"),
    (SRC / "extract" / "nats_d1_p39.png", "2012 US Nationals Day 1 Orlie Martin DS.png"),
    (SRC / "extract" / "nats_d1_p40.png", "2012 US Nationals Day 1 Leo Molitor DS.png"),
    (SRC / "extract" / "nats_d1_p41.png", "2012 US Nationals Day 1 Leo Molitor LS.png"),
    (SRC / "extract" / "nats_d1_p42.png", "2012 US Nationals Day 1 Brady LS.png"),
    (SRC / "extract" / "nats_d1_p43.png", "2012 US Nationals Day 1 Brady DS.png"),
    (SRC / "extract" / "nats_d1_p44.png", "2012 US Nationals Day 1 Scott Morgan DS.png"),
    (SRC / "extract" / "nats_d1_p45.png", "2012 US Nationals Day 1 Scott Morgan LS.png"),
    (SRC / "extract" / "nats_d1_p47.png", "2012 US Nationals Day 1 Aaron Nelson LS.png"),
    (SRC / "extract" / "nats_d1_p48.png", "2012 US Nationals Day 1 Jake Nelson LS.png"),
    (SRC / "extract" / "nats_d1_p49.png", "2012 US Nationals Day 1 Jake Nelson DS.png"),
    (SRC / "extract" / "nats_d1_p50.png", "2012 US Nationals Day 1 Mitch Nieland LS.png"),
    (SRC / "extract" / "nats_d1_p51.png", "2012 US Nationals Day 1 Mitch Nieland DS.png"),
    (SRC / "extract" / "nats_d1_p53.png", "2012 US Nationals Day 1 Jess Ojala LS.png"),
    (SRC / "extract" / "nats_d1_p52.png", "2012 US Nationals Day 1 Jess Ojala DS.png"),
    (SRC / "extract" / "nats_d1_p55.png", "2012 US Nationals Day 1 Nick Olson LS.png"),
    (SRC / "extract" / "nats_d1_p54.png", "2012 US Nationals Day 1 Nick Olson DS.png"),
    (SRC / "extract" / "nats_d1_p57.png", "2012 US Nationals Day 1 Alden Peterson LS.png"),
    (SRC / "extract" / "nats_d1_p56.png", "2012 US Nationals Day 1 Alden Peterson DS.png"),
    (SRC / "extract" / "nats_d1_p59.png", "2012 US Nationals Day 1 Mark Peterson LS.png"),
    (SRC / "extract" / "nats_d1_p58.png", "2012 US Nationals Day 1 Mark Peterson DS.png"),
    (SRC / "extract" / "nats_d1_p60.png", "2012 US Nationals Day 1 Jake Pietruszewski LS.png"),
    (SRC / "extract" / "nats_d1_p61.png", "2012 US Nationals Day 1 Jake Pietruszewski DS.png"),
    (SRC / "extract" / "nats_d1_p63.png", "2012 US Nationals Day 1 Nick Rambo LS.png"),
    (SRC / "extract" / "nats_d1_p62.png", "2012 US Nationals Day 1 Nick Rambo DS.png"),
    (SRC / "extract" / "nats_d1_p64.png", "2012 US Nationals Day 1 Chris Schoenthal LS.png"),
    (SRC / "extract" / "nats_d1_p65.png", "2012 US Nationals Day 1 Chris Schoenthal DS.png"),
    (SRC / "extract" / "nats_d1_p66.png", "2012 US Nationals Day 1 Matt Scott LS.png"),
    (SRC / "extract" / "nats_d1_p67.png", "2012 US Nationals Day 1 Matt Scott DS.png"),
    (SRC / "extract" / "nats_d1_p69.png", "2012 US Nationals Day 1 Kevin Shannon LS.png"),
    (SRC / "extract" / "nats_d1_p68.png", "2012 US Nationals Day 1 Kevin Shannon DS.png"),
    (SRC / "extract" / "nats_d1_p71.png", "2012 US Nationals Day 1 Conrad Simmering LS.png"),
    (SRC / "extract" / "nats_d1_p70.png", "2012 US Nationals Day 1 Conrad Simmering DS.png"),
    (SRC / "extract" / "nats_d1_p73.png", "2012 US Nationals Day 1 Zach Stenerson LS.png"),
    (SRC / "extract" / "nats_d1_p72.png", "2012 US Nationals Day 1 Zach Stenerson DS.png"),
    (SRC / "extract" / "nats_d1_p75.png", "2012 US Nationals Day 1 Nick Swedal LS.png"),
    (SRC / "extract" / "nats_d1_p74.png", "2012 US Nationals Day 1 Nick Swedal DS.png"),
    (SRC / "extract" / "nats_d1_p76.png", "2012 US Nationals Day 1 Matthew Ulstad LS.png"),
    (SRC / "extract" / "nats_d1_p77.png", "2012 US Nationals Day 1 Matthew Ulstad DS.png"),
    (SRC / "extract" / "nats_d1_p78.png", "2012 US Nationals Day 1 John Veasey LS.png"),
    (SRC / "extract" / "nats_d1_p80.png", "2012 US Nationals Day 1 John Veasey DS.png"),
    (SRC / "extract" / "nats_d1_p83.png", "2012 US Nationals Day 1 Mark Walseth LS.png"),
    (SRC / "extract" / "nats_d1_p82.png", "2012 US Nationals Day 1 Mark Walseth DS.png"),
    (SRC / "extract" / "nats_d1_p85.png", "2012 US Nationals Day 1 Hayes Hunter LS.png"),
    (SRC / "extract" / "nats_d1_p84.png", "2012 US Nationals Day 1 Hayes Hunter DS.png"),
    (SRC / "extract" / "nats_d1_p87.png", "2012 US Nationals Day 1 Unknown Player LS.png"),
    (SRC / "extract" / "nats_d1_p86.png", "2012 US Nationals Day 1 Unknown Player DS.png"),
    (SRC / "extract" / "nats_d2_p01.png", "2012 US Nationals Day 2 Angelo Consoli LS.png"),
    (SRC / "extract" / "nats_d2_p02.png", "2012 US Nationals Day 2 Angelo Consoli DS.png"),
    (SRC / "extract" / "nats_d2_p04.png", "2012 US Nationals Day 2 Tom Frafjord LS.png"),
    (SRC / "extract" / "nats_d2_p03.png", "2012 US Nationals Day 2 Tom Frafjord DS.png"),
    (SRC / "extract" / "nats_d2_p05.png", "2012 US Nationals Day 2 Brian Herold LS.png"),
    (SRC / "extract" / "nats_d2_p06.png", "2012 US Nationals Day 2 Brian Herold DS.png"),
    (SRC / "extract" / "nats_d2_p08.png", "2012 US Nationals Day 2 Aaron Nelson LS.png"),
    (SRC / "extract" / "nats_d2_p07.png", "2012 US Nationals Day 2 Aaron Nelson DS.png"),
    (SRC / "extract" / "nats_d2_p09.png", "2012 US Nationals Day 2 Jake Nelson LS.png"),
    (SRC / "extract" / "nats_d2_p10.png", "2012 US Nationals Day 2 Jake Nelson DS.png"),
    (SRC / "extract" / "nats_d2_p11.png", "2012 US Nationals Day 2 Kevin Shannon LS.png"),
    (SRC / "extract" / "nats_d2_p12.png", "2012 US Nationals Day 2 Kevin Shannon DS.png"),
]

for src, name in JOBS:
    dest = MEDIA / name
    shutil.copy2(src, dest)
    print("copy", src.name, "->", dest.name)
print("media", MEDIA)
