#!/usr/bin/env python3
import json
from pathlib import Path

m = json.loads(Path("wiki/card_title_map.json").read_text(encoding="utf-8"))
need = [
    "Wesa Gotta Grand Army",
    "We've Got To Get Away",
    "Affect Mind",
    "The Professor",
    "Don't Get Cocky",
    "Don't Do That Again",
    "Qui-Gon's Lightsaber",
    "Guardian's Lightsaber",
    "Kashyyyk: Forested Plains",
    "Communing",
    "Imperial Occupation",
    "Naboo: Boss Nass",
    "Qui-Gon With Lightsaber",
    "Leia With Blaster Rifle",
    "Speak With The Jedi",
    "Obi-Wan's Journal",
    "Yoda's Gimer Stick",
    "Anakin's Lightsaber",
    "Tantive IV",
    "Coruscant: Jedi Council Chamber",
    "Anger, Fear, Aggression",
    "There Is Good In Him",
    "I Feel The Conflict",
    "Seeking An Audience",
    "Sorry About The Mess",
    "Chewie, Enraged",
    "Han With Heavy Blaster Pistol",
    "Mace Windu, Master Of The Force",
    "Dark Approach",
    "Don't Tread On Me",
    "Anakin Skywalker, Padawan Learner",
    "A Jedi's Resilience",
    "Luke Skywalker, Rebel Scout",
    "Jabba's Prize",
    "Simple Tricks And Nonsense",
    "Yavin Sentry",
    "Chasm",
    "A Tragedy Has Occurred",
    "Rebel Leadership",
    "Cyclone Walker",
    "Stop Motion",
    "AT-AT Deployment",
    "Image Of The Dark Lord",
    "Image Of A Dark Lord",
    "Blizzard 2",
    "Garindan",
    "Overload",
    "Prepared Defenses",
    "Mind What You Have Learned",
    "Wookiee Slaving",
    "Imperial Entanglements",
    "Let The Wookiee Win",
    "I Had No Choice",
    "Control",
    "June Eclipse",
    "Master Kenobi",
    "Yoda, Great Warrior",
    "Shmi Skywalker",
    "Padme Naberrie",
    "Padmé Naberrie",
    "Wokling",
    "Sai'tor Kal Fas",
    "All Wings Report In",
    "Darklighter Spin",
    "Hear Me Baby",
    "K'lor'slug",
    "Luke's Bionic Hand",
    "Yub Yub",
    "Flash Of Insight",
    "Only Jedi Carry",
    "Do, Or Do Not",
    "Heading For The Medical Frigate",
    "Planetary Defense",
    "The Hyperdrive",
    "Obi-Wan's Hut",
    "Tatooine: Slave Quarters",
    "Hoth Occupation",
    "Marquand",
    "Tempest 1",
    "Flagship Executor",
    "I Had No Choice",
    "Walker Garrison",
    "Operational As Planned",
    "Target The Main Generator",
    "Wipe Them Out",
    "Hoth Blockade",
    "A Useless Gesture",
    "We'll Let Fate",
    "Come Here You Big Coward",
    "There Is No Try",
    "Death Star Sentry",
    "You Cannot Hide Forever",
    "Oppressive Enforcement",
    "Allegations Of Corruption",
    "Battle Order",
    "Abyss",
    "Fanfare",
    "After Her",
    "Secret Plans",
    "Firepower",
    "Resistance",
    "Knowledge And Defense",
    "Crash Landing",
    "Force Push",
    "Imperial Command",
    "A Dark Time For The Rebellion",
    "You May Start Your Landing",
    "Ni Chuba Na",
    "Endor Shield",
    "Blizzard 1",
    "Blizzard 4",
    "We're In Attack Position Now",
    "Do They Have A Code Clearance",
    "No Escape",
    "Cold Feet",
    "Close Call",
    "Deflector Shield Generators",
    "Elite Squadron Stormtrooper",
    "Imperial Stormtrooper",
    "Intensify The Forward Batteries",
    "A Dark Time For The Rebellion",
    "Outflank",
    "Trooper Assault",
    "Wounded Warrior",
    "Coordinated Attack",
    "Tatooine Occupation",
    "Imperial Academy Training",
    "Imperial Stockpile",
    "Strategic Reserves",
    "Imperial Domination",
    "Laser Cannon Battery",
    "Blaster Rifle",
    "Devastator",
    "Victory",
    "Mos Eisley",
    "Imperial Vanguard Camp",
    "Watto's Junkyard",
    "Imperial Outpost",
    "Mos Espa",
    "Jango Fett, The Assassin",
    "Ephant Mon",
    "Velken Tezeri",
    "Prince Xizor",
    "Dengar With Blaster Carbine",
    "Outer Rim Scout",
    "Ponda Baba",
    "Jabba The Hutt",
    "Mercenary Pilot",
    "Lady Valarian",
    "Bossk With Mortar Gun",
    "Boba Fett, Prepared Hunter",
    "IG-88 With Riot Gun",
    "OOM-9",
    "P-59",
    "4-LOM With Concussion Rifle",
    "Probot",
    "Something Special Planned For Them",
    "Hutt Bounty",
    "Den Of Thieves",
    "Special Delivery",
    "Scum And Villainy",
    "Jabba's Haven",
    "Power Of The Hutt",
    "Mercenary Slavers",
    "Search And Destroy",
    "Imperial Propaganda",
    "Ghhhk",
    "Elis Helrot",
    "Sonic Bombardment",
    "They're Still Coming Through",
    "Sith Fury",
    "End This Destructive Conflict",
    "Imperial Barrier",
    "Masterful Move",
    "Imbalance",
    "Kintan Strider",
    "Why Didn't You Tell Me",
    "Ommni Box",
    "It's Worse",
    "Monnok",
    "Short Range Fighters",
    "Watch Your Back",
    "Wookiee Subjugation",
    "Kashyyyk: Wookiee Slaving Camp",
    "Kashyyyk: Skyhook Platform",
    "Jabba's Sail Barge",
    "Kashyyyk: Slaving Camp Headquarters",
    "Nal Hutta",
    "Jabba's Space Cruiser",
    "Zuckuss In Mist Hunter",
    "Slave I, Symbol Of Fear",
    "Lando Calrissian, Unlikely Hero",
    "Threepio With His Parts Showing",
    "Yoda (V)",
    "Jaina Solo",
    "Wedge Antilles, Red Squadron Leader",
    "Luke Skywalker (V)",
    "Daughter Of Skywalker",
    "Major Haash'n",
    "General Airen Cracken",
    "Luke's Backpack",
    "Reflection (V)",
    "Launching The Assault",
    "Projection Of A Skywalker",
    "Much To Learn, You Still Have",
    "Battle Plan",
    "Draw Their Fire",
    "Do, Or Do Not",
    "Squadron Assignments",
    "The Way Of Things",
    "Legendary Starfighter",
    "Strong Is Vader",
    "It Is The Future You See",
    "We're Doomed",
    "A Few Maneuvers",
    "It Could Be Worse",
    "All Wings Report In",
    "Artoo-Detoo In Red 5",
    "Lady Luck",
    "Obi-Wan In Radiant VII",
    "Red Squadron 1",
    "Han, Chewie, And The Falcon",
    "Dagobah: Swamp",
    "Dagobah: Jungle",
    "Dagobah: Yoda's Hut",
    "Nar Shaddaa",
    "Home One: War Room",
    "Yavin 4: War Room",
    "Endor: Chief Chirpa's Hut",
    "Endor: Docking Bay",
    "Naboo: Battle Plains",
    "Lando Calrissian, Scoundrel",
    "Blaster Deflection",
    "Houjix",
    "Grimtaash",
    "Imperial Atrocity",
    "Jedi Levitation",
    "Escape Pod",
    "Nabrun Leids",
    "Clash Of Sabers",
    "Corran Horn",
    "Leia, Rebel Princess",
    "Admiral Ackbar",
    "Your Insight Serves You Well",
    "Ultimatum",
    "Wise Advice",
    "Aim High",
    "Let's Keep A Little Optimism Here",
    "Weapons Display",
    "Weapons Display (V)",
    "Admiral Motti",
    "Admiral Piett",
    "Elite Squadron Stormtrooper",
    "ISB Sector Commander",
    "Grand Admiral Thrawn",
    "Tatooine Occupation",
    "Endor Shield",
    "Imperial Academy Training",
    "Operational As Planned",
    "Outflank",
    "Trooper Assault",
    "Wounded Warrior",
    "Cold Feet",
    "Close Call",
    "Coordinated Attack",
    "Tatooine: Mos Eisley",
    "Tatooine: Imperial Vanguard Camp",
    "Tatooine: Watto's Junkyard",
    "Tatooine: Imperial Outpost",
    "Tatooine: Mos Espa",
    "Laser Cannon Battery",
    "Cyclone Walker",
    "Mara Jade With Lightsaber",
    "General Veers",
    "Image Of The Dark Lord",
    "AT-AT Deployment",
    "Darklighter Collector",
    "Sense (Dark)",
]
seen = set()
for q in need:
    ql = q.lower()
    hits = []
    for k, v in m.items():
        if ql in k.lower() or ql in v.lower():
            hits.append((k, v))
    if q in seen:
        continue
    seen.add(q)
    print("===", q, "===")
    if not hits:
        print("  NO HIT")
        continue
    for k, v in hits[:15]:
        print(f"  {k} => {v}")
    if len(hits) > 15:
        print("  ...", len(hits) - 15, "more")
